version: '3.8'

services:
  app:
    build: ./backend/
    ports:
      - "8000:80"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/movies
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: movies
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
