version: '3.8'

services:
  app:
    build: ./backend/
    ports:
      - "8000:80"
    env_file:
      - .env.local
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env.local
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
